//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDCA.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.questionaire_ans = new HashSet<questionaire_ans>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string degree_id { get; set; }
        public string faculty_id { get; set; }
    
        public virtual lut_course_faculty lut_course_faculty { get; set; }
        public virtual lut_edu_degree lut_edu_degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionaire_ans> questionaire_ans { get; set; }
    }
}
