//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDCA.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SWQUALEntities : DbContext
    {
        public DB_SWQUALEntities()
            : base("name=DB_SWQUALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auth_user> auth_user { get; set; }
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<lut_course_faculty> lut_course_faculty { get; set; }
        public virtual DbSet<lut_edu_degree> lut_edu_degree { get; set; }
        public virtual DbSet<plan> plan { get; set; }
        public virtual DbSet<questionaire> questionaire { get; set; }
        public virtual DbSet<questionaire_ans> questionaire_ans { get; set; }
        public virtual DbSet<questionaire_ans_point> questionaire_ans_point { get; set; }
        public virtual DbSet<questionaire_choice> questionaire_choice { get; set; }
    }
}
