//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDCA.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public questionaire()
        {
            this.questionaire_ans = new HashSet<questionaire_ans>();
            this.questionaire_choice = new HashSet<questionaire_choice>();
        }
    
        public int id { get; set; }
        public int year { get; set; }
        public string name { get; set; }
        public int owner_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionaire_ans> questionaire_ans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionaire_choice> questionaire_choice { get; set; }
    }
}
